version: '3'

services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
      - .:/app

    links:
    - db
    - rabbit
    entrypoint: ./docker-entrypoint.sh

  db:
   image: mysql:5.6
   ports:
    - "3306:3306"

   environment:
    MYSQL_ROOT_PASSWORD: "yes"
    MYSQL_DATABASE: lostandfound

  rabbit:
     hostname: rabbit
     image: rabbitmq:management
     environment:
       - RABBITMQ_DEFAULT_USER=rabbitmq
       - RABBITMQ_DEFAULT_PASS=rabbitmq
     ports:
       - "5673:5672"
       - "15672:15672"
  celery:
    build: .
    command: celery worker -A app.celery --loglevel=info
    volumes:
      - .:/app
    links:
      - rabbit


