version: '3'

services:
  web:
    build: .
    ports:
    - "5000:5000"

    links:
    - db
    entrypoint: ./docker-entrypoint.sh

  db:
   image: mysql:5.6
   ports:
    - "3306:3306"

   environment:
    MYSQL_ROOT_PASSWORD: "yes"
    MYSQL_DATABASE: lostandfound
    
    

